TabbedPanel:
    size_hint: 1, 1
    do_default_tab: False

    TabbedPanelItem:
        text: 'Pestaña 1'
        Label:
            text: 'Contenido tab1'

    TabbedPanelItem:
        text: 'Pestaña 2'
        BoxLayout:
            orientation: 'vertical'
            Label:
                text: 'contenido tab2'
            Button:
                text: 'Botón'

    TabbedPanelItem:
        text: 'Pestaña 3'
        BoxLayout:
            orientation: 'vertical'
            padding: 10
            spacing: 10
            Label:
                text: 'Nombre'
            TextInput:
                hint_text: 'Nombre'
            Label:
                text: 'Apellido'
            TextInput:
                hint_text: 'Apellido'
            Button:
                text: 'Enviar'